### ISSUE TITLE
optee-os fails to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by leon-anavi** [iotbzh/meta-optee#2]
Hi,

I noticed that recipe optee-os fails to build on Ubuntu 14.04. The following error is NOT observed on Ubuntu 16.04. It seems similar to the following issue: https://github.com/OP-TEE/optee_os/issues/663

Log:
<pre>
| Traceback (most recent call last):
|   File "scripts/pem_to_pub_c.py", line 79, in <module>
|     main()
|   File "scripts/pem_to_pub_c.py", line 45, in main
|     from Crypto.PublicKey import RSA
| ImportError: No module named Crypto.PublicKey
|   INSTALL /home/leon/optee/build-qemu-armv7/tmp/work/cortexa15hf-vfp-poky-linux-gnueabi/optee-os/1.0-r0/git/out/arm/export-ta_arm32/include/inttypes.h
| make: *** [/home/leon/optee/build-qemu-armv7/tmp/work/cortexa15hf-vfp-poky-linux-gnueabi/optee-os/1.0-r0/git/out/arm/core/ta_pub_key.c] Error 1
| make: *** Waiting for unfinished jobs....
|   INSTALL /home/leon/optee/build-qemu-armv7/tmp/work/cortexa15hf-vfp-poky-linux-gnueabi/optee-os/1.0-r0/git/out/arm/export-ta_arm32/include/sys/types.h
| make: Leaving directory `/home/leon/optee/build-qemu-armv7/tmp/work/cortexa15hf-vfp-poky-linux-gnueabi/optee-os/1.0-r0/git'
| ERROR: oe_runmake failed
| ERROR: Function failed: do_compile (log file is located at /home/leon/optee/build-qemu-armv7/tmp/work/cortexa15hf-vfp-poky-linux-gnueabi/optee-os/1.0-r0/temp/log.do_compile.19672)
ERROR: Task 6 (/home/leon/optee/poky/../meta-optee/recipes-bsp/optee-os/optee-os.bb, do_compile) failed with exit code '1'
</pre>

**Comment by vchong** [comment]
Looks like an OE build. Maybe python hasn't been built yet. Do you have the optee recipes depend on python? E.g.

`DEPENDS = "python-pycrypto-native python-wand-native"`

**Comment by leon-anavi** [comment]
Hi @vchong,

I have added a dependency to python-pycrypt. Please have a look at the commits related to optee-os in my GitHub pull request for details: https://github.com/iotbzh/meta-optee/pull/1

Furthermore I noticed that another layer withe same name exists as a sub directory in meta-linaro. Isn't it better to somehow merge both layers and use only one of them?

I will start a discussion in the AGL mailing list regarding these issues.

**Comment by vchong** [comment]
@leon-anavi 

> I have added a dependency to python-pycrypt. Please have a look at the commits related to optee-os in my GitHub pull request for details

Sorry but it's not clear if adding the dependency help resolve the issue?

> Furthermore I noticed that another layer withe same name exists as a sub directory in meta-linaro. Isn't it better to somehow merge both layers and use only one of them?

Yes but afaik https://github.com/iotbzh/ is not a Linaro projects so Linaro has no control over it. Assuming meta-linaro is upstream/mainline, and if the AGL project can use the recipes from meta-linaro directly, then it makes sense to just use them instead of writing new ones. If modifications are required then patches should be sent to meta-linaro. See https://git.linaro.org/openembedded/meta-linaro.git/blob/HEAD:/README under the 'Contributing' section for details.

**Comment by leon-anavi** [comment]
@vchong 
Yes, adding a dependency to python-pycrypt in the Yocto/OE recipe is required by pem_to_pub_c.py from recipe optee-os. You can see that this has been already done in Linaro's version of meta-optee. As I said optee-os builds fine on Ubuntu 16.04 but fails on Ubuntu 14.04.

I know that iot.bzh and Linaro and separate legal entities but we should find a way to work together on this because having two layers with different implementation and same name will cause a lot of confusion. We can either push changes from here to the Linaro repo or just use it and add AGL specific stuff through bbappend in meta-agl. 

@vchong I have already sent a report to the AGL mailing list. It is better to keep the discussion in a single place. Could you please join the conversation and share your thought there?
https://lists.linuxfoundation.org/pipermail/automotive-discussions/2016-June/002109.html

I have been informed that @Yanok35  is on vacation until the end of the week. I will chat with him next week.

**Comment by vchong** [comment]
@leon-anavi

> optee-os builds fine on Ubuntu 16.04 but fails on Ubuntu 14.04

This is purely by chance. The problem is still there and the same error can happen on a different Ubuntu 16.04 machine. Anyway, adding the DEPENDS will fix the issue regardless of versions so no worries.

> We can either push changes from here to the Linaro repo or just use it and add AGL specific stuff through bbappend in meta-agl.

+1. Either way sounds fine. You should be able to just use them without changes since the builds are pretty generic, but..

> I know that iot.bzh and Linaro and separate legal entities but we should find a way to work together on this because having two layers with different implementation and same name will cause a lot of confusion.
>I have already sent a report to the AGL mailing list. It is better to keep the discussion in a single place. Could you please join the conversation and share your thought there?
https://lists.linuxfoundation.org/pipermail/automotive-discussions/2016-June/002109.html

.. I'm not really the person to talk to regarding this. @jbech-linaro @fboudra @koenkooi @d3zd3z @kuscsik do you guys have any comments, either here or preferably on the mailing list above?

Thanks!

**Comment by vchong** [comment]
Hi,

I just wanted to note that I responded to this issue by accident. I started watching this repo recently and when the email notification for this issue arrived, I responded thinking that this was for https://github.com/OP-TEE/optee_os.

Sorry for any confusion caused.

**Comment by leon-anavi** [comment]
@vchong no worries, I highly appreciate your feedback. Thanks!

**Comment by fboudra** [comment]
@leon-anavi OP-TEE recipes for OpenEmbbeded have been started a long time before we created meta-optee. The plan is to get the recipes in shape, in meta-optee and then get them merged into meta-oe. Obviously, we plan to maintain them. I also expect the recipes maintain by us to be the reference (vs iot.bzh). I'll reply on the ml shortly. Thanks.
